---
apiVersion: bindplane.observiq.com/v1
kind: Source
metadata:
  name: grrcon-gateway-in
spec:
  type: bindplane_gateway
  parameters:
  - name: telemetry_types
    value:
    - Logs
  - name: listen_address
    value: 0.0.0.0
  - name: grpc_port
    value: 4317
  - name: http_port
    value: 4318
  - name: enable_tls
    value: false
---
apiVersion: bindplane.observiq.com/v2
kind: Configuration
metadata:
  name: grrcon-gateway
  labels:
    agent-type: observiq-otel-collector
    platform: linux
spec:
  sources:
  - id: s-grrcon-gateway-in
    name: grrcon-gateway-in
    routes:
      logs:
      - id: '0'
        components:
        - connectors/c-grrcon-router
  connectors:
  - id: c-grrcon-router
    name: grrcon-router
    routes:
      logs:
      - id: winsec
        components:
        - destinations/d-grrcon-google-secops
      - id: paloalto
        components:
        - destinations/d-grrcon-dynatrace
      - id: appjson
        components:
        - destinations/d-grrcon-google-gcl
      - id: apache
        components:
        - destinations/d-grrcon-elastic
      - id: cef
        components:
        - destinations/d-grrcon-splunk-hec
  destinations:
  - id: d-grrcon-google-secops
    name: grrcon-google-secops
  - id: d-grrcon-dynatrace
    name: grrcon-dynatrace
  - id: d-grrcon-google-gcl
    name: grrcon-google-gcl
  - id: d-grrcon-elastic
    name: grrcon-elastic
  - id: d-grrcon-splunk-hec
    name: grrcon-splunk-hec
  rollout:
    type: progressive
    parameters:
    - name: stages
      value:
      - name: Canary
        labels:
          env: canary
      - name: Prod
        labels:
          env: prod
    - name: maxErrors
      value: 0
    - name: phaseAgentCount
      value:
        type: adaptive
        initial: 0
        multiplier: 0
        maximum: 0
